### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by mc130h** [Manuel-Suarez-Abascal/ps5-bot#1]
[2020-11-17T05_29_19_444Z-debug.log](https://github.com/Manuel-Suarez-Abascal/ps5-bot/files/5551476/2020-11-17T05_29_19_444Z-debug.log)
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'cypress:open',
0 verbose cli   '--verbose'
0 verbose cli ]
1 info using npm@7.0.8
2 info using node@v15.2.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:c:\Users\Bryan\Desktop\ps5-bot-main\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\Bryan\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\Bryan\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 5ms
19 verbose npm-session f94185cb08584e06
20 timing npm:load Completed in 26ms
21 timing command:run-script Completed in 10ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:329:20)
22 verbose stack     at maybeClose (node:internal/child_process:1055:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
23 verbose pkgid ps5-bot@1.0.0
24 verbose cwd c:\Users\Bryan\Desktop\ps5-bot-main
25 verbose Windows_NT 10.0.19042
26 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "cypress:open" "--verbose"
27 verbose node v15.2.1
28 verbose npm  v7.0.8
29 error code 1
30 error path c:\Users\Bryan\Desktop\ps5-bot-main
31 error command failed
32 error command C:\Windows\system32\cmd.exe /d /s /c "./node_modules/.bin/cypress open"
33 verbose exit 1

**Comment by Manuel-Suarez-Abascal** [comment]
@mc130h I have updated the documentation. Start from scratch from cloning the project, to install the dependencies & run it again. Make sure to read the docs carefully. If you need help, post it here & I'll do my best to help you out. The bot will be deleted( probably*) from Github after Black Friday sales.

**Comment by mc130h** [comment]
Getting this failure:
c:\Users\Bryan\Desktop\ps5>npm run cypress:open

> ps5-bot@1.0.0 cypress:open
> ./node_modules/.bin/cypress open

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path c:\Users\Bryan\Desktop\ps5
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c
"./node_modules/.bin/cypress open"

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\Bryan\AppData\Local\npm-cache\_logs\2020-11-17T22_13_38_873Z-debug.log

c:\Users\Bryan\Desktop\ps5>npm run cypress:open --verbose
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'cypress:open',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.0.8
npm info using node@v15.2.1
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc
Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:c:\Users\Bryan\Desktop\ps5\.npmrc Completed in
0ms
npm timing config:load:project Completed in 0ms
npm timing config:load:file:C:\Users\Bryan\.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:C:\Users\Bryan\AppData\Roaming\npm\etc\npmrc
Completed in 0ms
npm timing config:load:global Completed in 1ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 6ms
npm verb npm-session 4c49b7f4397c4605
npm timing npm:load Completed in 29ms

> ps5-bot@1.0.0 cypress:open
> ./node_modules/.bin/cypress open

'.' is not recognized as an internal or external command,
operable program or batch file.
npm timing command:run-script Completed in 10ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Program
Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:329:20)
npm verb stack     at maybeClose (node:internal/child_process:1055:16)
npm verb stack     at Process.ChildProcess._handle.onexit
(node:internal/child_process:288:5)
npm verb pkgid ps5-bot@1.0.0
npm verb cwd c:\Users\Bryan\Desktop\ps5
npm verb Windows_NT 10.0.19042
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "cypress:open"
"--verbose"
npm verb node v15.2.1
npm verb npm  v7.0.8
npm ERR! code 1
npm ERR! path c:\Users\Bryan\Desktop\ps5
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c
"./node_modules/.bin/cypress open"
npm verb exit 1
npm timing npm Completed in 214ms

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\Bryan\AppData\Local\npm-cache\_logs\2020-11-17T22_13_45_205Z-debug.log

**Comment by Manuel-Suarez-Abascal** [comment]
@mc130h I think it's related to `node_modules/.bin/` path. I have updated the npm script. Try recloning the project, install dependencies & retrying now!
