### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by mc130h** [Manuel-Suarez-Abascal/ps5-bot#2]
Before running the project, I opened cypress.json file and input my credentials as instructed. 
Then proceeded with the remainder of the steps, get the environment loaded, and chrome pops up.
It loads the webpage base url to https://www.walmart.com/account/login
Then get this error:
0
AssertionError
Timed out retrying: Expected to find element: #username, but never found it.
cypress/support/commands.js:30:8
  28 |   (username = Cypress.env("username"), password = Cypress.env("password")) => {
  29 |     cy.visit(Cypress.env("baseUrl"));
> 30 |     cy.get("#username").type(username);
     |        ^
  31 |     cy.get("#password").type(password);
  32 |     cy.get("#login-form").submit();
  33 |   }

I verified my info is input. Wondering if the Walmart login website saying Email address (required) instead of username makes a difference, and if not, what the issue could be?

**Comment by mc130h** [comment]
Update: If I change the base url to walmart.ca it will indeed place my credentials into the required blocks. Seems like a compatibility error with the us.

**Comment by Manuel-Suarez-Abascal** [comment]
> Update: If I change the base url to walmart.ca it will indeed place my credentials into the required blocks. Seems like a compatibility error with the us.

I see, so I assume it's working for you now? @mc130h ? If it's the case good luck with your purchase ;)

**Comment by mc130h** [comment]
I mean, it works on the .ca site, though, I’m not from Canada. Nor do I have a Canadian Walmart account. So it doesn’t login. Therefore, not able to use it.

**Comment by Manuel-Suarez-Abascal** [comment]
@mc130h it won't work in a `walmart.com` website just in `walmart.ca`. I wrote [in the docs](https://github.com/Manuel-Suarez-Abascal/ps5-bot#few-notes). Unfortunately, the `walmart.com` uses different selectors & purchase flow so I didn't include on my bot because it's not my usecase. You could, however, reverse engineer the bot to make work in `walmart.com`

**Comment by Manuel-Suarez-Abascal** [comment]
I will close this issue, I encourage you to fork the project & and play with it & reuse the code to get it to work in `walmart.com` it reads almost like English tbh.
